#!/bin/sh
VERSION=`egrep BUILD_VERSION version.h | sed -e 's/^[^"]*"//' -e 's/".*$//'`
echo "Building nickle $VERSION RPM..." >&2
RPMBUILD=$HOME/rpmbuild
echo mkdir -p $RPMBUILD/nickle-$VERSION
make nickle-$VERSION.tar.gz
cp nickle-$VERSION.tar.gz $RPMBUILD/nickle-$VERSION
cp nickle.spec nickle-$VERSION.spec
ed nickle-$VERSION.spec << EOF
/VERSION/s//$VERSION/
w
q
EOF
rpm -ba nickle-$VERSION.spec
